# Generated by Django 3.0.2 on 2020-02-06 09:08

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='deals',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[service.models.validate_positive], verbose_name='Деньги'),
        ),
    ]
